import { NextResponse } from 'next/server';
import { getDatabase } from '@/lib/db/mongodb';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

const DATABASE_NAME = 'roj-kuch-naya';
const COLLECTION_NAME = 'posts';
const QUIZ_LIMIT = 5;

type SourcePost = {
  _id: unknown;
  title?: string;
  metaDescription?: string;
};

type QuizQuestion = {
  _id: string;
  type: 'mcq';
  question: string;
  options: string[];
  correctAnswer: string;
};

function normalizeTitle(value: unknown, index: number): string {
  if (typeof value === 'string' && value.trim()) {
    return value.trim();
  }

  return `General Knowledge Update ${index + 1}`;
}

function pickDistractors(titles: string[], correct: string, index: number): string[] {
  const pool = titles.filter((title) => title !== correct);

  const selected: string[] = [];
  for (let i = 0; i < pool.length && selected.length < 3; i += 1) {
    const candidate = pool[(index + i) % pool.length];
    if (candidate && !selected.includes(candidate)) {
      selected.push(candidate);
    }
  }

  while (selected.length < 3) {
    selected.push(`Practice concept ${selected.length + 1}`);
  }

  return selected;
}

function buildAutoQuestions(posts: SourcePost[]): QuizQuestion[] {
  const titles = posts.map((post, index) => normalizeTitle(post.title, index));

  return posts.slice(0, QUIZ_LIMIT).map((post, index) => {
    const correctAnswer = normalizeTitle(post.title, index);
    const distractors = pickDistractors(titles, correctAnswer, index);
    const options = [correctAnswer, ...distractors];
    const rotated = options.map((_, i) => options[(i + index) % options.length]);

    return {
      _id: `auto-${String(post._id ?? index)}`,
      type: 'mcq',
      question: `Which headline matches this summary: ${post.metaDescription ?? 'Read and choose the best matching title.'}`,
      options: rotated,
      correctAnswer
    };
  });
}

export async function GET() {
  try {
    const db = await getDatabase();

    if (db.databaseName !== DATABASE_NAME) {
      throw new Error(`Connected to unexpected database: ${db.databaseName}`);
    }

    const collection = db.collection(COLLECTION_NAME);

    const questions = await collection
      .aggregate([{ $match: { type: 'mcq' } }, { $sample: { size: QUIZ_LIMIT } }])
      .toArray();

    if (questions.length > 0) {
      return NextResponse.json({ success: true, questions });
    }

    const sourcePosts = (await collection
      .find({ status: 'published' }, { projection: { title: 1, metaDescription: 1 } })
      .sort({ createdAt: -1 })
      .limit(10)
      .toArray()) as SourcePost[];

    const autoQuestions = buildAutoQuestions(sourcePosts);

    return NextResponse.json({
      success: true,
      questions: autoQuestions,
      autogenerated: true
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        message: error instanceof Error ? error.message : 'Failed to fetch quiz questions.'
      },
      { status: 500 }
    );
  }
}
