import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config();

import Post from '../lib/models/post.js'; // Make sure this file exists as ES module

import OpenAI from 'openai';

// Validate env variables
if (!process.env.MONGODB_URI) throw new Error("Missing environment variable: MONGODB_URI");
if (!process.env.AI_API_KEY) throw new Error("Missing environment variable: AI_API_KEY");

// Initialize OpenAI
const openai = new OpenAI({ apiKey: process.env.AI_API_KEY });

// Connect to MongoDB
async function connectMongo() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ MongoDB connected');
  } catch (err) {
    console.error('❌ MongoDB connection failed:', err);
    process.exit(1);
  }
}

// Example AI content generation for Delhi news
async function generateContent() {
  try {
    const prompt = "Write 5 latest news in Hindi about Delhi with SEO friendly title";
    const response = await openai.chat.completions.create({
      model: "gpt-4",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7
    });

    const content = response.choices[0].message?.content;
    if (!content) throw new Error("No content generated by AI");

    // Save to MongoDB
    const post = new Post({ title: "Delhi News", content, category: "news", date: new Date() });
    await post.save();

    console.log('✅ AI content generated and saved');
  } catch (err) {
    console.error('❌ AI generation failed:', err);
  }
}

async function main() {
  await connectMongo();
  await generateContent();
  mongoose.disconnect();
}

main();
